SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_MAX_SPEED = 70
ASTEROID_MIN_SPEED = 20

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 100
PLAYER_LIVES = 3
PLAYER_ACCELERATION = 220 
PLAYER_FRICTION = 0.85      
PLAYER_MAX_SPEED = 300
PLAYER_INVULNERABLE_DURATION = 3.0    


SHOT_RADIUS = 5
SHOT_DURATION = 180
PLAYER_SHOOT_SPEED = 350
PLAYER_SHOOT_COOLDOWN = 0.35

EXPLOSION_PARTICLE_COUNT = 30
EXPLOSION_DURATION = 50
EXPLOSION_MIN_SPEED = 1.5
EXPLOSION_MAX_SPEED = 8
EXPLOSION_FRICTION = 0.85